# Iniciación a la programación (limpieza de datos y bucles)

* La librería Pandas
* Importacion de librerias para manejo de archivos Excel
* Elementos más importantes
* Filtrado de Datos
* Busqueda de Valores Nulos
* Unión de Archivos
* Agrupacion de Valores
* Tablas Dinámicas (Resumen)

### Librerias de importación / Exportación en Excel

In [ ]:
#Para archivos *.xls -> pip install xlwt

In [ ]:
#Para archivos *.xlsx -> pip install openpyxl

In [1]:
import pandas as pd

In [ ]:
titanic = pd.read_excel("./Data/Titanic.xlsx", sheet_name = "Titanic") #leer archivos
titanic.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

### Elementos más importantes

In [4]:
titanic.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [5]:
titanic.describe(include = ["O"])

                    Name   Sex    Ticket            Cabin Embarked
count                418   418       418               91      418
unique               418     2       363               76        3
top     Kelly, Mr. James  male  PC 17608  B57 B59 B63 B66        S
freq                   1   266         5                3      270

In [6]:
titanic.shape

(418, 11)

In [7]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [8]:
titanic.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
titanic.columns = ['Id_Pasajero', 'Pclass', 'Nombre', 'Sexo', 'Edad', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked']
titanic.columns

Index(['Id_Pasajero', 'Pclass', 'Nombre', 'Sexo', 'Edad', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [10]:
titanic.head()

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [11]:
titanic.columns[0] = "ID_Pasajero"

TypeError: Index does not support mutable operations

### Filtrado de Datos

In [12]:
titanic.head()

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [13]:
titanic["Ticket"]

0                  330911
1                  363272
2                  240276
3                  315154
4                 3101298
              ...
413             A.5. 3236
414              PC 17758
415    SOTON/O.Q. 3101262
416                359309
417                  2668
Name: Ticket, Length: 418, dtype: object

In [14]:
titanic[["Edad", "Sexo"]]

     Edad    Sexo
0    34.5    male
1    47.0  female
2    62.0    male
3    27.0    male
4    22.0  female
..    ...     ...
413   NaN    male
414  39.0  female
415  38.5    male
416   NaN    male
417   NaN    male

[418 rows x 2 columns]

In [15]:
titanic["Edad"].mean()

30.272590361445783

In [16]:
titanic["Edad"].std()

14.18120923562442

In [17]:
titanic["Edad"].median()

27.0

In [18]:
titanic["Edad"].min()

0.17

In [19]:
titanic["Sexo"]

0        male
1      female
2        male
3        male
4      female
        ...
413      male
414    female
415      male
416      male
417      male
Name: Sexo, Length: 418, dtype: object

In [20]:
titanic["Sexo"][1]

'female'

In [21]:
titanic["Sexo"][20]

'male'

In [22]:
type(titanic["Sexo"][3])

str

In [23]:
titanic["Nombre"][13]

'Howard, Mr. Benjamin'

In [24]:
titanic["Edad"] > 40

0      False
1       True
2       True
3      False
4      False
       ...
413    False
414    False
415    False
416    False
417    False
Name: Edad, Length: 418, dtype: bool

In [5]:
titanic[titanic["Edad"] > 40]

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
11,903,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,NaN,S
13,905,2,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
...,...,...,...,...,...,...,...,...,...,...,...
391,1283,1,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)",female,51.0,0,1,PC 17592,39.4000,D28,S
393,1285,2,"Gilbert, Mr. William",male,47.0,0,0,C.A. 30769,10.5000,NaN,S
397,1289,1,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",female,48.0,1,1,13567,79.2000,B41,C
404,1296,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
407,1299,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C

In [6]:
titanic[titanic["Edad"] > 40][["Nombre", "Id_Pasajero"]]

                                                Nombre  Id_Pasajero
1                     Wilkes, Mrs. James (Ellen Needs)          893
2                            Myles, Mr. Thomas Francis          894
11                          Jones, Mr. Charles Cresson          903
13                                Howard, Mr. Benjamin          905
14   Chaffee, Mrs. Herbert Fuller (Carrie Constance...          906
..                                                 ...          ...
391     Lines, Mrs. Ernest H (Elizabeth Lindsey James)         1283
393                               Gilbert, Mr. William         1285
397  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...         1289
404                       Frauenthal, Mr. Isaac Gerald         1296
407                         Widener, Mr. George Dunton         1299

[77 rows x 2 columns]

In [ ]:
#Sería si ambos son ciertos usamos "&"
#Sería si alguno es cierto usamos "|"
#Si es contrario "~"

In [7]:
titanic[(titanic["Sexo"] == "female") & (titanic["Edad"] < 50)]

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
...,...,...,...,...,...,...,...,...,...,...,...
402,1294,1,"Gibson, Miss. Dorothy Winifred",female,22.0,0,1,112378,59.4000,NaN,C
409,1301,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [8]:
titanic[(titanic["Pclass"] == 2) | (titanic["Embarked"] == "S")]

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
409,1301,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S

In [9]:
titanic[~(titanic["Sexo"] == "female")]

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
407,1299,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [10]:
titanic[(~(titanic["Embarked"] == "S")) & (titanic["Sexo"] != "male")]

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,NaN,C
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
...,...,...,...,...,...,...,...,...,...,...,...
402,1294,1,"Gibson, Miss. Dorothy Winifred",female,22.0,0,1,112378,59.4000,NaN,C
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [11]:
titanic[(titanic["Embarked"] != "S") | (titanic["Sexo"] != "male")]

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [12]:
# Filtrar por condicion de que empiece con "A" para columna de texto

titanic[titanic["Nombre"].str.startswith("B")]

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
28,920,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S
48,940,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.0,0,0,11813,76.2917,D15,C
62,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.0,0,0,347090,7.7500,NaN,S
63,955,3,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q
66,958,3,"Burns, Miss. Mary Delia",female,18.0,0,0,330963,7.8792,NaN,Q
80,972,3,"Boulos, Master. Akar",male,6.0,1,1,2678,15.2458,NaN,C
86,978,3,"Barry, Miss. Julia",female,27.0,0,0,330844,7.8792,NaN,Q
87,979,3,"Badman, Miss. Emily Louisa",female,18.0,0,0,A/4 31416,8.0500,NaN,S
94,986,1,"Birnbaum, Mr. Jakob",male,25.0,0,0,13905,26.0000,NaN,C
98,990,3,"Braf, Miss. Elin Ester Maria",female,20.0,0,0,347471,7.8542,NaN,S
106,998,3,"Buckley, Mr. Daniel",male,21.0,0,0,330920,7.8208,NaN,Q
113,1005,3,"Buckley, Miss. Katherine",female,18.5,0,0,329944,7.2833,NaN,Q
118,1010,1,"Beattie, Mr. Thomson",male,36.0,0,0,13050,75.2417,C6,C
126,1018,3,"Brobeck, Mr. Karl Rudolf",male,22.0,0,0,350045,7.7958,NaN,S
128,1020,2,"Bowenur, Mr. Solomon",male,42.0,0,0,211535,13.0000,NaN,S
143,1035,2,"Beauchamp, Mr. Henry James",male,28.0,0,0,244358,26.0000,NaN,S
156,1048,1,"Bird, Miss. Ellen",female,29.0,0,0,PC 17483,221.7792,C97,S
158,1050,1,"Borebank, Mr. John James",male,42.0,0,0,110489,26.5500,D22,S
166,1058,1,"Brandeis, Mr. Emil",male,48.0,0,0,PC 17591,50.4958,B10,C
175,1067,2,"Brown, Miss. Edith Eileen",female,15.0,0,2,29750,39.0000,NaN,S
178,1070,2,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.0,0,3,230136,39.0000,F4,S
198,1090,2,"Baimbrigge, Mr. Charles Robert",male,23.0,0,0,C.A. 31030,10.5000,NaN,S
237,1129,3,"Baccos, Mr. Raffull",male,20.0,0,0,2679,7.2250,NaN,C
258,1150,2,"Bentham, Miss. Lilian W",female,19.0,0,0,28404,13.0000,NaN,S
275,1167,2,"Bryhl, Miss. Dagmar Jenny Ingeborg",female,20.0,1,0,236853,26.0000,NaN,S
326,1218,2,"Becker, Miss. Ruth Elizabeth",female,12.0,2,1,230136,39.0000,F4,S
339,1231,3,"Betros, Master. Seman",male,NaN,0,0,2622,7.2292,NaN,C
346,1238,2,"Botsford, Mr. William Hull",male,26.0,0,0,237670,13.0000,NaN,S
356,1248,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0,2,0,11769,51.4792,C101,S
375,1267,1,"Bowen, Miss. Grace Scott",female,45.0,0,0,PC 17608,262.3750,NaN,C
400,1292,1,"Bonnell, Miss. Caroline",female,30.0,0,0,36928,164.8667,C7,S

In [14]:
titanic_excel = titanic[(~(titanic["Embarked"] == "S")) & (titanic["Sexo"] != "male")].reset_index()
titanic_excel

,index,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
1,8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
2,15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
3,19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,NaN,C
4,24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
...,...,...,...,...,...,...,...,...,...,...,...,...
59,402,1294,1,"Gibson, Miss. Dorothy Winifred",female,22.0,0,1,112378,59.4000,NaN,C
60,408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
61,410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
62,411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
63,414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [15]:
titanic_excel.to_excel("titanic_excel.xlsx", sheet_name = "Datos_Titanic", index = False)

In [16]:
titanic_excel.to_csv("titanic_csv.csv", sep = ";")

In [17]:
titanic[(titanic["Edad"] > 65) | (titanic["Edad"] < 10)]

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
21,913,3,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.1708,NaN,S
80,972,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.2458,NaN,C
81,973,1,"Straus, Mr. Isidor",male,67.00,1,0,PC 17483,221.7792,C55 C57,S
89,981,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,NaN,S
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.00,1,0,19877,78.8500,C46,S
117,1009,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.7000,G6,S
161,1053,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.2458,NaN,C
194,1086,2,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.5000,NaN,S
196,1088,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.5000,E34,C
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S
203,1095,2,"Quick, Miss. Winifred Vera",female,8.00,1,1,26360,26.0000,NaN,S
250,1142,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,NaN,S
263,1155,3,"Klasen, Miss. Gertrud Emilia",female,1.00,1,1,350405,12.1833,NaN,S
281,1173,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
283,1175,3,"Touma, Miss. Maria Youssef",female,9.00,1,1,2650,15.2458,NaN,C
284,1176,3,"Rosblom, Miss. Salli Helena",female,2.00,1,1,370129,20.2125,NaN,S
296,1188,2,"Laroche, Miss. Louise",female,1.00,1,2,SC/Paris 2123,41.5792,NaN,C
307,1199,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S
354,1246,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.5750,NaN,S
379,1271,3,"Asplund, Master. Carl Edgar",male,5.00,4,2,347077,31.3875,NaN,S
389,1281,3,"Palsson, Master. Paul Folke",male,6.00,3,1,349909,21.0750,NaN,S
409,1301,3,"Peacock, Miss. Treasteall",female,3.00,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S

In [18]:
titanic[(titanic["Edad"] < 65) & (titanic["Edad"] > 10)]

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
407,1299,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S

In [19]:
titanic.sort_values("Edad")

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
354,1246,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.5750,NaN,S
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S
281,1173,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
307,1199,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S
250,1142,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [20]:
titanic.sort_values("Edad", ascending = False)

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S
81,973,1,"Straus, Mr. Isidor",male,67.0,1,0,PC 17483,221.7792,C55 C57,S
236,1128,1,"Warren, Mr. Frank Manley",male,64.0,1,0,110813,75.2500,D37,C
305,1197,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.0,1,1,112901,26.5500,B26,S
179,1071,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.0,0,2,PC 17756,83.1583,E45,C
...,...,...,...,...,...,...,...,...,...,...,...
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [21]:
titanic["Sexo"].value_counts()

male      266
female    152
Name: Sexo, dtype: int64

In [22]:
titanic["Embarked"].value_counts()

S    270
C    102
Q     46
Name: Embarked, dtype: int64

In [23]:
titanic_excel

,index,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
1,8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
2,15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
3,19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,NaN,C
4,24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
...,...,...,...,...,...,...,...,...,...,...,...,...
59,402,1294,1,"Gibson, Miss. Dorothy Winifred",female,22.0,0,1,112378,59.4000,NaN,C
60,408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
61,410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
62,411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
63,414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [24]:
titanic_excel.drop(["index"], axis = 1)

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
1,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
2,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
3,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,NaN,C
4,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
...,...,...,...,...,...,...,...,...,...,...,...
59,1294,1,"Gibson, Miss. Dorothy Winifred",female,22.0,0,1,112378,59.4000,NaN,C
60,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
61,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
62,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
63,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [25]:
titanic_excel

,index,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
1,8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
2,15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
3,19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,NaN,C
4,24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
...,...,...,...,...,...,...,...,...,...,...,...,...
59,402,1294,1,"Gibson, Miss. Dorothy Winifred",female,22.0,0,1,112378,59.4000,NaN,C
60,408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
61,410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
62,411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
63,414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [26]:
titanic_excel.drop(["index"], axis = 1, inplace = True)

In [27]:
titanic_excel

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
1,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
2,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
3,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,NaN,C
4,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
...,...,...,...,...,...,...,...,...,...,...,...
59,1294,1,"Gibson, Miss. Dorothy Winifred",female,22.0,0,1,112378,59.4000,NaN,C
60,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
61,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
62,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
63,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [28]:
titanic["Columna_nueva"] = titanic["SibSp"] + titanic["Parch"]
titanic

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Columna_nueva
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,0
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,2

In [29]:
titanic["Columna_nueva_2"] = "Espacio vacio"
titanic

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Columna_nueva,Columna_nueva_2
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,Espacio vacio
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1,Espacio vacio
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,Espacio vacio
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,Espacio vacio
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2,Espacio vacio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0,Espacio vacio
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,0,Espacio vacio
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,Espacio vacio
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0,Espacio vacio
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,2,Espacio vacio

In [30]:
titanic["Edad_años"] = round(titanic["Edad"] + 0.01, 0)
titanic

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Columna_nueva,Columna_nueva_2,Edad_años
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,Espacio vacio,35.0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1,Espacio vacio,47.0
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,Espacio vacio,62.0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,Espacio vacio,27.0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2,Espacio vacio,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0,Espacio vacio,NaN
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,0,Espacio vacio,39.0
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,Espacio vacio,39.0
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0,Espacio vacio,NaN
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,2,Espacio vacio,NaN

### Busqueda de Valores Nulos

In [31]:
titanic["Edad"]

0      34.5
1      47.0
2      62.0
3      27.0
4      22.0
       ...
413     NaN
414    39.0
415    38.5
416     NaN
417     NaN
Name: Edad, Length: 418, dtype: float64

In [32]:
titanic["Edad"].isna()

0      False
1      False
2      False
3      False
4      False
       ...
413     True
414    False
415    False
416     True
417     True
Name: Edad, Length: 418, dtype: bool

In [33]:
titanic["Edad"].isna().sum()

86

In [34]:
titanic.isna().sum()

Id_Pasajero          0
Pclass               0
Nombre               0
Sexo                 0
Edad                86
SibSp                0
Parch                0
Ticket               0
Fare                 1
Cabin              327
Embarked             0
Columna_nueva        0
Columna_nueva_2      0
Edad_años           86
dtype: int64

In [35]:
titanic.isna().sum().sort_values(ascending = False)

Cabin              327
Edad                86
Edad_años           86
Fare                 1
Id_Pasajero          0
Pclass               0
Nombre               0
Sexo                 0
SibSp                0
Parch                0
Ticket               0
Embarked             0
Columna_nueva        0
Columna_nueva_2      0
dtype: int64

In [36]:
titanic.isna().sum().sort_values(ascending = False).head(6)

Cabin          327
Edad            86
Edad_años       86
Fare             1
Id_Pasajero      0
Pclass           0
dtype: int64

In [37]:
titanic.isna().sum().sum()

500

### Unión de Archivos

In [38]:
df1 = pd.DataFrame({'Frutas': ['manzana', 'naranja', 'pera', 'mango'],
                    'precios': [1, 2, 3, 5]})
df2 = pd.DataFrame({'Frutas y Verduras': ['manzana', 'zanahoria', 'tomate', 'pera'],
                    'precios': [5, 6, 7, 8]})

In [39]:
df1

    Frutas  precios
0  manzana        1
1  naranja        2
2     pera        3
3    mango        5

In [40]:
df2

  Frutas y Verduras  precios
0           manzana        5
1         zanahoria        6
2            tomate        7
3              pera        8

In [41]:
pd.merge(df1, df2, how = "inner", on = "precios")

  Frutas  precios Frutas y Verduras
0  mango        5           manzana

In [42]:
pd.merge(df1, df2, how = "left", on = "precios")

    Frutas  precios Frutas y Verduras
0  manzana        1               NaN
1  naranja        2               NaN
2     pera        3               NaN
3    mango        5           manzana

In [43]:
pd.merge(df1, df2, how = "right", on = "precios")

  Frutas  precios Frutas y Verduras
0  mango        5           manzana
1    NaN        6         zanahoria
2    NaN        7            tomate
3    NaN        8              pera

In [44]:
pd.merge(df1, df2, how = "outer", on = "precios")

    Frutas  precios Frutas y Verduras
0  manzana        1               NaN
1  naranja        2               NaN
2     pera        3               NaN
3    mango        5           manzana
4      NaN        6         zanahoria
5      NaN        7            tomate
6      NaN        8              pera

In [45]:
df_1 = pd.DataFrame({'Frutas': ['manzana', 'naranja', 'pera', 'mango'],
                     'unidades':[34, 82, 15, 20],
                    'id_vendedor': [1, 2, 3, 5]})
df_2 = pd.DataFrame({'Frutas y Verduras': ['manzana', 'zanahoria', 'tomate', 'pera'],
                     'unidades':[72, 41, 70, 2],
                    'id_vendedor': [5, 6, 7, 8]})
df_1

    Frutas  unidades  id_vendedor
0  manzana        34            1
1  naranja        82            2
2     pera        15            3
3    mango        20            5

In [46]:
df_2

  Frutas y Verduras  unidades  id_vendedor
0           manzana        72            5
1         zanahoria        41            6
2            tomate        70            7
3              pera         2            8

In [47]:
pd.merge(df_1, df_2, how = "left", on = "id_vendedor", suffixes = ("_tabla1", "_tabla2"))

    Frutas  unidades_tabla1  id_vendedor Frutas y Verduras  unidades_tabla2
0  manzana               34            1               NaN              NaN
1  naranja               82            2               NaN              NaN
2     pera               15            3               NaN              NaN
3    mango               20            5           manzana             72.0

In [48]:
pd.concat([df1, df2], axis = 1)

    Frutas  precios Frutas y Verduras  precios
0  manzana        1           manzana        5
1  naranja        2         zanahoria        6
2     pera        3            tomate        7
3    mango        5              pera        8

In [49]:
pd.concat([df1, df2], axis = 0)

    Frutas  precios Frutas y Verduras
0  manzana        1               NaN
1  naranja        2               NaN
2     pera        3               NaN
3    mango        5               NaN
0      NaN        5           manzana
1      NaN        6         zanahoria
2      NaN        7            tomate
3      NaN        8              pera

In [50]:
pd.concat([df1, df2], axis = 0, ignore_index = True)

    Frutas  precios Frutas y Verduras
0  manzana        1               NaN
1  naranja        2               NaN
2     pera        3               NaN
3    mango        5               NaN
4      NaN        5           manzana
5      NaN        6         zanahoria
6      NaN        7            tomate
7      NaN        8              pera

In [51]:
pd.concat([df1, df2], axis = 0, ignore_index = True)[["Frutas", "Frutas y Verduras"]]

    Frutas Frutas y Verduras
0  manzana               NaN
1  naranja               NaN
2     pera               NaN
3    mango               NaN
4      NaN           manzana
5      NaN         zanahoria
6      NaN            tomate
7      NaN              pera

### Agrupacion de Valores

In [52]:
titanic["Sexo"].value_counts()

male      266
female    152
Name: Sexo, dtype: int64

In [53]:
titanic["Embarked"].value_counts()

S    270
C    102
Q     46
Name: Embarked, dtype: int64

In [54]:
titanic["Embarked"].nunique()

3

In [55]:
titanic["Embarked"].unique()

array(['Q', 'S', 'C'], dtype=object)

### Tablas Dinámicas (Tablas Resumen)

In [56]:
import numpy as np

In [57]:
titanic.pivot_table(index = "Sexo", columns = "Pclass", values = "Id_Pasajero", aggfunc = "nunique")

Pclass   1   2    3
Sexo
female  50  30   72
male    57  63  146

In [58]:
titanic.pivot_table(index = ["Sexo", "Pclass"], columns = ["Embarked"], values = "Id_Pasajero", aggfunc = "nunique")

Embarked          C     Q      S
Sexo   Pclass
female 1       28.0   1.0   21.0
       2        4.0   NaN   26.0
       3        8.0  23.0   41.0
male   1       28.0   NaN   29.0
       2        7.0   4.0   52.0
       3       27.0  18.0  101.0

In [59]:
titanic.pivot_table(index = ["Sexo", "Pclass"], columns = ["Embarked"], values = "Id_Pasajero", aggfunc = "nunique", 
                   fill_value = 0)

Embarked        C   Q    S
Sexo   Pclass
female 1       28   1   21
       2        4   0   26
       3        8  23   41
male   1       28   0   29
       2        7   4   52
       3       27  18  101

In [60]:
titanic.pivot_table(index = ["Sexo", "Parch"], columns = ["Embarked"], values = "Edad", aggfunc = np.median, 
                   fill_value = 0.0)

Embarked         C     Q     S
Sexo   Parch
female 0      36.0  25.5  24.5
       1      24.0   0.0  18.0
       2      32.5   0.0  28.0
       3      48.0   0.0  36.0
       4       0.0   0.0  60.0
male   0      30.5  31.0  27.0
       1      37.0  10.0  27.5
       2      13.0   0.0  13.0
       3      61.0   0.0   0.0
       5       0.0   0.0  40.0
       6       0.0   0.0  40.0

In [61]:
titanic.pivot_table(index = ["Embarked"], columns = ["Sexo", "Parch"], values = "Edad", aggfunc = np.median, 
                   fill_value = 0.0)

Sexo     female                    male
Parch         0   1     2   3   4     0     1   2   3   5   6
Embarked
C          36.0  24  32.5  48   0  30.5  37.0  13  61   0   0
Q          25.5   0   0.0   0   0  31.0  10.0   0   0   0   0
S          24.5  18  28.0  36  60  27.0  27.5  13   0  40  40

In [62]:
titanic

,Id_Pasajero,Pclass,Nombre,Sexo,Edad,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Columna_nueva,Columna_nueva_2,Edad_años
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,Espacio vacio,35.0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1,Espacio vacio,47.0
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,Espacio vacio,62.0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,Espacio vacio,27.0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2,Espacio vacio,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0,Espacio vacio,NaN
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,0,Espacio vacio,39.0
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,Espacio vacio,39.0
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0,Espacio vacio,NaN
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,2,Espacio vacio,NaN

In [63]:
titanic.T

,0,1,2,3,4,5,6,7,8,9,...,408,409,410,411,412,413,414,415,416,417
Id_Pasajero,892,893,894,895,896,897,898,899,900,901,...,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309
Pclass,3,3,2,3,3,3,3,2,3,3,...,3,3,3,1,3,3,1,3,3,3
Nombre,"Kelly, Mr. James","Wilkes, Mrs. James (Ellen Needs)","Myles, Mr. Thomas Francis","Wirz, Mr. Albert","Hirvonen, Mrs. Alexander (Helga E Lindqvist)","Svensson, Mr. Johan Cervin","Connolly, Miss. Kate","Caldwell, Mr. Albert Francis","Abrahim, Mrs. Joseph (Sophie Halaut Easu)","Davies, Mr. John Samuel",...,"Riordan, Miss. Johanna Hannah""""","Peacock, Miss. Treasteall","Naughton, Miss. Hannah","Minahan, Mrs. William Edward (Lillian E Thorpe)","Henriksson, Miss. Jenny Lovisa","Spector, Mr. Woolf","Oliva y Ocana, Dona. Fermina","Saether, Mr. Simon Sivertsen","Ware, Mr. Frederick","Peter, Master. Michael J"
Sexo,male,female,male,male,female,male,female,male,female,male,...,female,female,female,female,female,male,female,male,male,male
Edad,34.5,47.0,62.0,27.0,22.0,14.0,30.0,26.0,18.0,21.0,...,NaN,3.0,NaN,37.0,28.0,NaN,39.0,38.5,NaN,NaN
SibSp,0,1,0,0,1,0,0,1,0,2,...,0,1,0,1,0,0,0,0,0,1
Parch,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,1
Ticket,330911,363272,240276,315154,3101298,7538,330972,248738,2657,A/4 48871,...,334915,SOTON/O.Q. 3101315,365237,19928,347086,A.5. 3236,PC 17758,SOTON/O.Q. 3101262,359309,2668
Fare,7.8292,7.0,9.6875,8.6625,12.2875,9.225,7.6292,29.0,7.2292,24.15,...,7.7208,13.775,7.75,90.0,7.775,8.05,108.9,7.25,8.05,22.3583
Cabin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,C78,NaN,NaN,C105,NaN,NaN,NaN
Embarked,Q,S,Q,S,S,S,Q,S,C,S,...,Q,S,Q,Q,S,S,C,S,S,C
Columna_nueva,0,1,0,0,2,0,0,2,0,2,...,0,2,0,1,0,0,0,0,0,2
Columna_nueva_2,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,...,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio,Espacio vacio
Edad_años,35.0,47.0,62.0,27.0,22.0,14.0,30.0,26.0,18.0,21.0,...,NaN,3.0,NaN,37.0,28.0,NaN,39.0,39.0,NaN,NaN