# Iniciación a la programación (limpieza de datos y bucles)

* Tipos de Datos
* Funciones Básicas del Lenguaje
* Funciones Especiales
* Variables
* Listas, Tuplas y Diccionarios
* Condicional If
* Bucles For y While
* Creación de Funciones Personalizadas
* Clases y Objetos
* La librería numpy
* Funciones Más Utilizadas
* La librería Pandas
* Las Series
* Los Dataframes
* Cargar y Guardar Archivos

### Tipos de Datos

In [1]:
# Integer

4

4

In [2]:
# Float

3.14

3.14

In [3]:
# Strings

"Texto"

'Texto'

In [4]:
'Texto'

'Texto'

In [5]:
# Boolean

True

True

In [6]:
False

False

### Funciones Básicas del Lenguaje

In [7]:
# Sumar (Concatenar)

100 + 25

125

In [8]:
2 + 1.0

3.0

In [9]:
"Texto de " + "prueba"

'Texto de prueba'

In [10]:
# Restar

20 - 15

5

In [11]:
0 - 5

-5

In [12]:
25 - 17.0

8.0

In [13]:
# Multiplicación

8 * 4

32

In [14]:
# División

6 / 3

2.0

In [15]:
1 / 3

0.3333333333333333

In [16]:
2 / 0

ZeroDivisionError: division by zero

In [17]:
# Potenciación

#9^2
9 ** 2

81

In [18]:
5 ** 3

125

In [19]:
# Division Entera

2 // 3

0

In [20]:
2 / 3

0.6666666666666666

In [21]:
15 // 3

5

In [22]:
15 / 3

5.0

In [23]:
16 // 3

5

In [24]:
# Modulo

15 % 2

1

In [25]:
50 % 5

0

In [26]:
76 % 14

6

### Funciones Especiales

In [27]:
# Valor absoluto

abs(-5)

5

In [28]:
# Redondear

round(1.23)

1

In [29]:
round(2.5)

2

In [30]:
round(2.500001)

3

In [31]:
round(3.6)

4

In [13]:
round(4.649874967, ndigits = 2)

4.65

In [32]:
# Conversion a Entero

int(5.5)

5

In [33]:
int("5")

5

In [34]:
# Conversión a Decimal

float(4)

4.0

In [35]:
# Conversion a Cadena (String)

str(23)

'23'

In [36]:
# Extraer valor máximo

max(1, -4, 25)

25

In [37]:
# Extraer valor mínimo

min(1, -4, 25)

-4

In [38]:
min(abs(1), abs(-4), abs(25))

1

In [39]:
# Función print

print("5")

5

In [40]:
"Resultado 1"

3

3

In [41]:
print("Resultado 1")

3

Resultado 1

3

In [42]:
# Función type

type(1)

int

In [43]:
type(3.7)

float

In [44]:
type("Hola mundo")

str

In [45]:
type('Hola mundo')

str

In [46]:
type(True)

bool

In [47]:
type(False)

bool

In [48]:
# Funcion Range

range(0, 3) # 0, 1, 2

range(0, 3)

### Variables

In [1]:
variable1 = 5
variable1

5

In [2]:
variable2 = 10

In [3]:
variable2

10

In [4]:
variable3 = variable1 * variable2
variable3

50

In [5]:
variable1 = 17
variable1

17

In [6]:
variable3

50

In [7]:
variable3 = variable1 * variable2
variable3

170

In [8]:
variable = 27
variable

27

In [9]:
VARIABLE = 47
VARIABLE

47

In [10]:
variable

27

In [11]:
Variable_1 = 0
Variable_1

0

In [12]:
Variable

NameError: name 'Variable' is not defined

In [13]:
%who

VARIABLE	 Variable_1	 variable	 variable1	 variable2	 variable3

In [14]:
%whos

Variable     Type    Data/Info
------------------------------
VARIABLE     int     47
Variable_1   int     0
variable     int     27
variable1    int     17
variable2    int     10
variable3    int     170

In [15]:
# Comparadores

3 == 5 #Igual

False

In [16]:
3 == 3

True

In [17]:
3 != 5 #Diferente

True

In [18]:
3 < 5 #Menor que

True

In [19]:
3 <= 5 #Menor o igual que

True

In [20]:
3 <= 3

True

In [21]:
3 > 5 #Mayor que

False

In [22]:
3 >= 5 #Mayor o igual que

False

In [23]:
"business" == "Business"

False

In [24]:
"business" == "busIness"

False

In [25]:
"business" == "business"

True

In [26]:
"business" == 'business'

True

### Listas, Tuplas y Diccionarios

In [27]:
lista1 = ["Diana", "Carlos", "Isaac", "Lilibeth", "Miguel", "Reinerio"]
lista1

['Diana', 'Carlos', 'Isaac', 'Lilibeth', 'Miguel', 'Reinerio']

In [28]:
lista1[0]

'Diana'

In [29]:
lista1[3]

'Lilibeth'

In [30]:
lista1[:]

['Diana', 'Carlos', 'Isaac', 'Lilibeth', 'Miguel', 'Reinerio']

In [31]:
lista1[2:]

['Isaac', 'Lilibeth', 'Miguel', 'Reinerio']

In [32]:
lista1[:4]

['Diana', 'Carlos', 'Isaac', 'Lilibeth']

In [33]:
lista1[:]

['Diana', 'Carlos', 'Isaac', 'Lilibeth', 'Miguel', 'Reinerio']

In [34]:
lista1[2:5]

['Isaac', 'Lilibeth', 'Miguel']

In [35]:
lista1[:3]

['Diana', 'Carlos', 'Isaac']

In [36]:
lista1[3:]

['Lilibeth', 'Miguel', 'Reinerio']

In [37]:
lista1[:3] + lista1[3:]

['Diana', 'Carlos', 'Isaac', 'Lilibeth', 'Miguel', 'Reinerio']

In [38]:
lista1[-1]

'Reinerio'

In [39]:
lista1[::-1]

['Reinerio', 'Miguel', 'Lilibeth', 'Isaac', 'Carlos', 'Diana']

In [40]:
len(lista1)

6

In [41]:
# Agregar valores

lista1.append("Samuel")
lista1

['Diana', 'Carlos', 'Isaac', 'Lilibeth', 'Miguel', 'Reinerio', 'Samuel']

In [42]:
lista1.insert(2, "Daniel")
lista1

['Diana',
 'Carlos',
 'Daniel',
 'Isaac',
 'Lilibeth',
 'Miguel',
 'Reinerio',
 'Samuel']

In [43]:
# Eliminar valores

lista1.remove("Miguel")
lista1

['Diana', 'Carlos', 'Daniel', 'Isaac', 'Lilibeth', 'Reinerio', 'Samuel']

In [44]:
lista1.pop(-3)
lista1

['Diana', 'Carlos', 'Daniel', 'Isaac', 'Reinerio', 'Samuel']

In [45]:
lista1[-1] = "Zamuel"
lista1

['Diana', 'Carlos', 'Daniel', 'Isaac', 'Reinerio', 'Zamuel']

In [46]:
type(lista1)

list

In [47]:
# Tuplas

tupla1 = ("Diana", "Carlos", "Isaac", "Lilibeth", "Miguel", "Reinerio")
tupla1

('Diana', 'Carlos', 'Isaac', 'Lilibeth', 'Miguel', 'Reinerio')

In [48]:
tupla1[4]

'Miguel'

In [49]:
tupla1[2] = "Samuel"
tupla1

TypeError: 'tuple' object does not support item assignment

In [50]:
type(tupla1)

tuple

In [51]:
# Diccionario

Diccionario1 = {"manzana": 3,
               "pera": 4,
               "naranjas": 7,
               "melocoton": 6,
               "sandia": 10}
Diccionario1

{'manzana': 3, 'pera': 4, 'naranjas': 7, 'melocoton': 6, 'sandia': 10}

In [52]:
Diccionario1.keys()

dict_keys(['manzana', 'pera', 'naranjas', 'melocoton', 'sandia'])

In [53]:
Diccionario1.values()

dict_values([3, 4, 7, 6, 10])

In [54]:
Diccionario1["manzana"]

3

In [55]:
Diccionario2 = {"manzana": [3, 10],
               "pera": [4, 25],
               "naranjas": [7, 20],
               "melocoton": [6, 6],
               "sandia": [10, 4]}
Diccionario2

{'manzana': [3, 10],
 'pera': [4, 25],
 'naranjas': [7, 20],
 'melocoton': [6, 6],
 'sandia': [10, 4]}

In [56]:
Diccionario2["manzana"]

[3, 10]

In [57]:
Diccionario2["manzana"][1]

10

In [58]:
Diccionario2.values()

dict_values([[3, 10], [4, 25], [7, 20], [6, 6], [10, 4]])

In [59]:
type(Diccionario1)

dict

### Condicional If

In [60]:
lista2 = [19, 30, 42, 57, 73, 21]
lista2

[19, 30, 42, 57, 73, 21]

In [61]:
lista2[2]

42

In [62]:
lista2[1]

30

In [ ]:
if (condicion):
    Se ejecuta cuando condicion == True

In [63]:
if lista2[1] >= 20:
    print("Eres mayor de edad")

Eres mayor de edad

In [64]:
if lista2[0] >= 20:
    print("Eres mayor de edad")

In [65]:
if lista2[1] >= 20:
    print("Eres mayor de edad")
else:
    print("Eres menor de edad")

Eres mayor de edad

In [66]:
if lista2[0] >= 20:
    print("Eres mayor de edad")
else:
    print("Eres menor de edad")

Eres menor de edad

In [67]:
if lista2[1] >= 70:
    print("Eres un adulto mayor")
elif lista2[1] >= 20:
    print("Eres un adulto")
else:
    print("Eres muy joven")

Eres un adulto

In [68]:
if lista2[0] >= 70:
    print("Eres un adulto mayor")
elif lista2[0] >= 20:
    print("Eres un adulto")
else:
    print("Eres muy joven")

Eres muy joven

In [69]:
if lista2[-2] >= 70:
    print("Eres un adulto mayor")
elif lista2[-2] >= 20:
    print("Eres un adulto")
else:
    print("Eres muy joven")

Eres un adulto mayor

In [ ]:
var = 25

if condicion1 == True: # Comentarios de una línea
    if condicion2 == True: 
        if condicion3 == False:
            var = 100
        else:
            pass
    else:
        pass
else:
    pass

""" 
Esto es un comentario de más de una línea


"""

### Bucles For y While

In [70]:
print(0)
print(1)
print(2)
print(3)
print(4)

0
1
2
3
4

In [71]:
for i in range(0, 5): # [0, 1, 2, 3, 4]
    print(i)

0
1
2
3
4

In [72]:
for i in [0, 1, 2, 3, 4]:
    print(i)

0
1
2
3
4

In [73]:
for i in range(0, 5):
    i

In [74]:
for var_0 in range(0, 4):
    for var_1 in range(0, 5):
        print(var_0 , var_1)

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4

In [75]:
for var0 in range(0, 4):
    for var1 in range(0, 5):
        if var0 == var1:
            print(var0 , var1)

0 0
1 1
2 2
3 3

In [76]:
for j in range(0, 6):
    if j == 3:
        pass
    else:
        print(j)

0
1
2
4
5

In [77]:
for estudiantes in lista1:
    print(estudiantes)

Diana
Carlos
Daniel
Isaac
Reinerio
Zamuel

In [78]:
for pos_estudiantes in range(0, len(lista1)):
    print(lista1[pos_estudiantes])

Diana
Carlos
Daniel
Isaac
Reinerio
Zamuel

In [79]:
for pos_estudiantes in range(0, len(lista1)):
    print(pos_estudiantes)

0
1
2
3
4
5

In [80]:
i = 1
while i < 10:
    print(i)
    i = i + 1
    #i += 1

1
2
3
4
5
6
7
8
9

### Funciones personalizadas

In [ ]:
def funcionpersonalizada(a, b):
    c = a + b
    return c

In [81]:
def sumar(numero1, numero2):
    numero3 = numero1 + numero2
    return numero3

In [82]:
sumar(5, 6)

11

In [83]:
"2" + 3

TypeError: can only concatenate str (not "int") to str

In [84]:
sumar("2", 3)

TypeError: can only concatenate str (not "int") to str

In [85]:
def multiplica3(var):
    return var*3

In [86]:
multiplica3(10)

30

In [87]:
multiplica3("a")

'aaa'

In [88]:
sumar(int("5"), 6)

11

In [89]:
def funcion():
    return 1 + 2

In [90]:
funcion()

3

In [91]:
for i in range(1,4):
    print(sumar(i, 3))

4
5
6

### Clases y Objetos

In [92]:
class Miobjeto():
    def __init__(var):
        self.var = 15        
    variable = "Hola Mundo"

In [93]:
perro = Miobjeto

In [94]:
perro.variable

'Hola Mundo'

### La librería Numpy

In [1]:
import numpy as np

In [2]:
#Constantes

print(np.pi) #Pi
np.e #e

3.141592653589793

2.718281828459045

In [3]:
np.log(np.e) #logaritmo natural

1.0

In [4]:
np.log(100)

4.605170185988092

In [5]:
lista = [0, 4, 5, 1, 5]
lista

[0, 4, 5, 1, 5]

In [6]:
a = np.array(lista, dtype = float) #
a

array([0., 4., 5., 1., 5.])

In [7]:
type(a)

numpy.ndarray

In [8]:
a[1]

4.0

In [9]:
a.astype(int)

array([0, 4, 5, 1, 5])

In [10]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
a.shape

(5,)

In [14]:
b.shape

(3, 4)

In [15]:
b.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747475,
       0.75757576, 0.76767677, 0.77777778, 0.78787879, 0.7979798 ,
       0.80808081, 0.81818182, 0.82828283, 0.83838384, 0.84848485,
       0.85858586, 0.86868687, 0.87878788, 0.88888889, 0.8989899 ,
       0.90909091, 0.91919192, 0.92929293, 0.93939394, 0.94949495,
       0.95959596, 0.96969697, 0.97979798, 0.98989899, 1.        ])

In [17]:
np.cos(10)

-0.8390715290764524

In [18]:
np.sin(10)

-0.5440211108893698

### La librería Pandas

In [19]:
import pandas as pd

In [20]:
lista1 = ["Diana", "Carlos", "Isaac", "Lilibeth", "Miguel", "Reinerio"]
lista1

['Diana', 'Carlos', 'Isaac', 'Lilibeth', 'Miguel', 'Reinerio']

In [21]:
serie = pd.Series(lista1)
serie

0       Diana
1      Carlos
2       Isaac
3    Lilibeth
4      Miguel
5    Reinerio
dtype: object

In [22]:
type(serie)

pandas.core.series.Series

In [23]:
pd.DataFrame({"color": ["blanco", "gris", "negro"], "número": [255, 100, 0]})

    color  número
0  blanco     255
1    gris     100
2   negro       0

In [ ]:
df = pd.read_csv("./Data/coffee-prices-historical-data.csv", sep = ",")
df

             date   value
0      1973-08-20  0.6735
1      1973-08-21  0.6710
2      1973-08-22  0.6580
3      1973-08-23  0.6675
4      1973-08-24  0.6660
...           ...     ...
12558  21.08.2023     NaN
12559  22.08.2023     NaN
12560  23.08.2023     NaN
12561  24.08.2023     NaN
12562  25.08.2023     NaN

[12563 rows x 2 columns]

In [25]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
#df1 = pd.read_excel("archivo.xlsx", sheet_name = "Sheet1")
#df1

In [26]:
df.head(10)

         date   value
0  1973-08-20  0.6735
1  1973-08-21  0.6710
2  1973-08-22  0.6580
3  1973-08-23  0.6675
4  1973-08-24  0.6660
5  1973-08-27  0.6590
6  1973-08-28  0.6400
7  1973-08-29  0.6345
8  1973-08-30  0.6387
9  1973-08-31  0.6402

In [27]:
df.tail(7)

             date   value
12556  19.08.2023     NaN
12557  20.08.2023     NaN
12558  21.08.2023     NaN
12559  22.08.2023     NaN
12560  23.08.2023     NaN
12561  24.08.2023     NaN
12562  25.08.2023     NaN

In [28]:
df.describe()

              value
count  12542.000000
mean       1.289773
std        0.490239
min        0.425000
25%        0.960500
50%        1.248500
75%        1.510000
max        3.356300

In [29]:
df.describe(include=["O"])

              date
count        12563
unique       12563
top     1973-08-20
freq             1