### Reglas de Datos Parte 2
* Curvas ROC - AUC
* Extracción de Conocimiento en la Mineria de Datos
* Reglas de Asociación en la Mineria de Datos
* Aplicaciones de las Reglas de Asociación
* Reglas de Clasificación en la Mineria de Datos
* Algoritmos de Aprendizaje de Reglas de Asociación
* Algoritmos de Aprendizaje de Reglas de Clasificación

### Curvas ROC - AUC

![ROC](https://upload.wikimedia.org/wikipedia/commons/b/b9/Curvas.png)

### Extracción de Conocimiento en la Mineria de Datos

![Extraccion](https://discoversdkcdn.azureedge.net/postscontent/ayala/Beautiful-Soup_VS_SCRAPY.png)

![MD](https://i0.wp.com/www.baoss.es/wp-content/uploads/2021/01/KDD.png?ssl=1)

### Reglas de Asociación en la Mineria de Datos

![Asociacion](https://elbauldelprogramador.com/img/rulesMaximals.jpg)

![Asocia](https://www.ugr.es/~rruizb/cognosfera/sala_de_estudio/ciencimetria_redes_conocimiento/images/image40.gif)

In [ ]:
Items (columnas) [I] y Transacciones (filas) [T]

T x I

In [ ]:
Regla de Asociación

A (antecedente) -> B (consecuente)

In [ ]:
A ∩ B = ∅

1. El soporte es una medida que contabiliza la frecuencia en la cual los términos de una regla de asociación se encuentran en los datos, es decir, el número de transacciones en las cuales los ítems presentes en una regla ocurren juntos en los datos en relación con el número total de transacciones.

2. La medida de confianza se refiere a un valor de correspondencia entre los ítems que componen una regla, es decir, la medida denota el porcentaje de transacciones que contienen conjuntamente el término antecedente y el término consecuente en relación al número de transacciones que contienen la parte antecedente. 

3. Lift o “sustentación” es una medida de interés que tiene como propósito analizar el grado de dependencia entro los elementos que conforman una regla.

In [ ]:
Objetivo sería encontrar reglas que posean

1. Alto soporte
2. Alta confianza
3. Alto lift

### Aplicaciones de las Reglas de Asociación

* Validación de grado de asociación de grandes volúmenes de datos.
* Análisis del comportamiento de los clientes en compras de mercado.
* Análisis del comportamiento de los clientes en préstamos de libros.
* Diseño de Herramientas para prueba de resistencia de choques en automóviles.
* Análisis de calidad y cantidad de reglas de asociación.
* Utilización de Computación en Paralelo para el análisis de grandes volúmenes de datos.
* Creación de nuevos algoritmos optimizados que permitan analizar de forma rápida y eficiente grandes volúmenes de datos.
* Creación de nuevas tecnologías para la detección de intrusiones basadas en reglas de asociación.

### Reglas de Clasificación en la Mineria de Datos

![RCMD](https://i0.wp.com/www.jacobsoft.com.mx/wp-content/uploads/2018/10/arbol_test.png?fit=765%2C586&ssl=1)

In [ ]:
Regla de Clasificación

A (antecedente) -> B (consecuente)

In [ ]:
A ∩ B != ∅

### Algoritmos de Aprendizaje de Reglas de Asociación

* A priori
* Frequent Parent Growth (FPGrowth)
* Algoritmo QFP
* CBA
* CMAR
* CPAR

### Algoritmos de Aprendizaje de Reglas de Clasificación

* Arboles de decisión (Algoritmo C4.5)
* Arboles recortados como el método PART

### Preparación de los Datos para Reglas de asociación

In [1]:
import pandas as pd

In [ ]:
datos_crudos = pd.read_csv("./Data/orders.csv", sep = ";")
datos_crudos

        order_id              product_name
0              2        Organic Egg Whites
1              2     Michigan Organic Kale
2              2             Garlic Powder
3              2            Coconut Butter
4              2         Natural Sweetener
...          ...                       ...
296995     31319  Uncured Black Forest Ham
296996     31319            Pizza 4 Cheese
296997     31320         Soft Potato Bread
296998     31320                 Spaghetti
296999     31320      Marinara Pasta Sauce

[297000 rows x 2 columns]

In [3]:
datos_crudos["Suma"] = 1
datos_crudos

        order_id              product_name  Suma
0              2        Organic Egg Whites     1
1              2     Michigan Organic Kale     1
2              2             Garlic Powder     1
3              2            Coconut Butter     1
4              2         Natural Sweetener     1
...          ...                       ...   ...
296995     31319  Uncured Black Forest Ham     1
296996     31319            Pizza 4 Cheese     1
296997     31320         Soft Potato Bread     1
296998     31320                 Spaghetti     1
296999     31320      Marinara Pasta Sauce     1

[297000 rows x 3 columns]

In [4]:
datos_crudos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297000 entries, 0 to 296999
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      297000 non-null  int64
 1   product_name  297000 non-null  object
 2   Suma          297000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 6.8+ MB

In [5]:
datos_pre = datos_crudos.pivot_table(index = 'order_id', columns = 'product_name', aggfunc = 'sum', values = "Suma")
datos_pre

MemoryError: Unable to allocate 5.43 GiB for an array with shape (29432, 24748) and data type float64

In [6]:
datos_crudos["order_id"].nunique()

29432

In [7]:
datos_crudos["product_name"].nunique()

24748

In [ ]:
datos_prep = datos_pre.iloc[:5000]
datos_prep

In [ ]:
datos_listos = datos_prep.fillna(0)
datos_listos

In [ ]:
datos_listos.to_csv("Reglas_Asociacion.csv")